[package]
name = "graphest-webp-sys"
version = "0.1.0"
authors = ["Masashi Mizuno"]
edition = "2021"
repository = "https://github.com/unageek/graphest"
license = "MIT"
publish = false

[build-dependencies]
bindgen = "*"

[lib]
doctest = false
test = false
