export enum Command {
  AbortGraphing = "abort-graphing",
  ExportImage = "export-image",
  HighResolution = "high-resolution",
  NewDocument = "new-document",
  Open = "open",
  OpenFromClipboard = "open-from-clipboard",
  Preferences = "preferences",
  Save = "save",
  SaveAs = "save-as",
  SaveToClipboard = "save-to-clipboard",
  ShowAxes = "show-axes",
  ShowMajorGrid = "show-major-grid",
  ShowMinorGrid = "show-minor-grid",
}
